name: CI Workflow
on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17 # Specify your Java version
          distribution: 'temurin' # You can use 'zulu', 'adopt', etc.
          cache: 'maven' # Enable dependency caching for Maven

      - name: Compile the code
        run: mvn compile

#  static-analysis:
#    runs-on: ubuntu-latest
#    needs: compile
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v3
#
#      - name: Set up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'temurin'
#          cache: 'maven'
#
#      - name: Run Static Analysis
#        run: mvn checkstyle:check

  unit-tests:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn test

  code-coverage:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Code Coverage Report
        run: mvn test jacoco:report