name: CI Workflow
on:
  push:
    branches:
      - master

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: display a success message
        run: echo "Welcome to GitHub Actions!"
      - name: display the present working directory
        run: |
          pwd
          ls
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: execute maven commands
        run: mvn package
      - name: display the contents of the folder after maven execution
        run: ls
